Trying 127.0.0.1...
Connected to localhost.localdomain.
Escape character is '^]'.
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE GANGLIA_XML [
   <!ELEMENT GANGLIA_XML (GRID|CLUSTER|HOST)*>
      <!ATTLIST GANGLIA_XML VERSION CDATA #REQUIRED>
      <!ATTLIST GANGLIA_XML SOURCE CDATA #REQUIRED>
   <!ELEMENT GRID (CLUSTER | GRID | HOSTS | METRICS)*>
      <!ATTLIST GRID NAME CDATA #REQUIRED>
      <!ATTLIST GRID AUTHORITY CDATA #REQUIRED>
      <!ATTLIST GRID LOCALTIME CDATA #IMPLIED>
   <!ELEMENT CLUSTER (HOST | HOSTS | METRICS)*>
      <!ATTLIST CLUSTER NAME CDATA #REQUIRED>
      <!ATTLIST CLUSTER OWNER CDATA #IMPLIED>
      <!ATTLIST CLUSTER LATLONG CDATA #IMPLIED>
      <!ATTLIST CLUSTER URL CDATA #IMPLIED>
      <!ATTLIST CLUSTER LOCALTIME CDATA #REQUIRED>
   <!ELEMENT HOST (METRIC)*>
      <!ATTLIST HOST NAME CDATA #REQUIRED>
      <!ATTLIST HOST IP CDATA #REQUIRED>
      <!ATTLIST HOST LOCATION CDATA #IMPLIED>
      <!ATTLIST HOST REPORTED CDATA #REQUIRED>
      <!ATTLIST HOST TN CDATA #IMPLIED>
      <!ATTLIST HOST TMAX CDATA #IMPLIED>
      <!ATTLIST HOST DMAX CDATA #IMPLIED>
      <!ATTLIST HOST GMOND_STARTED CDATA #IMPLIED>
   <!ELEMENT METRIC EMPTY>
      <!ATTLIST METRIC NAME CDATA #REQUIRED>
      <!ATTLIST METRIC VAL CDATA #REQUIRED>
      <!ATTLIST METRIC TYPE (string | int8 | uint8 | int16 | uint16 | int32 | uint32 | float | double | timestamp) #REQUIRED>
      <!ATTLIST METRIC UNITS CDATA #IMPLIED>
      <!ATTLIST METRIC TN CDATA #IMPLIED>
      <!ATTLIST METRIC TMAX CDATA #IMPLIED>
      <!ATTLIST METRIC DMAX CDATA #IMPLIED>
      <!ATTLIST METRIC SLOPE (zero | positive | negative | both | unspecified) #IMPLIED>
      <!ATTLIST METRIC SOURCE (gmond | gmetric) #REQUIRED>
   <!ELEMENT HOSTS EMPTY>
      <!ATTLIST HOSTS UP CDATA #REQUIRED>
      <!ATTLIST HOSTS DOWN CDATA #REQUIRED>
      <!ATTLIST HOSTS SOURCE (gmond | gmetric | gmetad) #REQUIRED>
   <!ELEMENT METRICS EMPTY>
      <!ATTLIST METRICS NAME CDATA #REQUIRED>
      <!ATTLIST METRICS SUM CDATA #REQUIRED>
      <!ATTLIST METRICS NUM CDATA #REQUIRED>
      <!ATTLIST METRICS TYPE (string | int8 | uint8 | int16 | uint16 | int32 | uint32 | float | double | timestamp) #REQUIRED>
      <!ATTLIST METRICS UNITS CDATA #IMPLIED>
      <!ATTLIST METRICS SLOPE (zero | positive | negative | both | unspecified) #IMPLIED>
      <!ATTLIST METRICS SOURCE (gmond | gmetric) #REQUIRED>
]>
<GANGLIA_XML VERSION="3.0.0" SOURCE="gmetad">
<GRID NAME="Beowulf Systems" AUTHORITY="http://monitor2/ganglia/" LOCALTIME="1111153080">
<CLUSTER NAME="LISA Cluster" LOCALTIME="1111153070" OWNER="SARA" LATLONG="unspecified" URL="unspecified">
<HOST NAME="gb-r2n13.irc.sara.nl" IP="192.168.17.33" REPORTED="1111153066" TN="14" TMAX="20" DMAX="0" LOCATION="unspecified" GMOND_STARTED="1108725342">
<METRIC NAME="disk_free" VAL="139.454" TYPE="double" UNITS="GB" TN="32" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="mtu" VAL="1500" TYPE="uint32" UNITS="B" TN="242" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="machine_type" VAL="x86" TYPE="string" UNITS="" TN="787" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="bytes_out" VAL="43.35" TYPE="float" UNITS="bytes/sec" TN="197" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="gexec" VAL="OFF" TYPE="string" UNITS="" TN="129" TMAX="300" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="proc_total" VAL="72" TYPE="uint32" UNITS="" TN="70" TMAX="950" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_constrain_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="pkts_in" VAL="241.42" TYPE="float" UNITS="packets/sec" TN="182" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_nice" VAL="0.0" TYPE="float" UNITS="%" TN="52" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_speed" VAL="3392" TYPE="uint32" UNITS="MHz" TN="428" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="boottime" VAL="1108725320" TYPE="timestamp" UNITS="s" TN="242" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Symbol_error_counter" VAL="19" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_VL15_dropped" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Port_transmit_packets" VAL="4294967295" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="os_name" VAL="Linux" TYPE="string" UNITS="" TN="401" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="sys_clock" VAL="1108725342" TYPE="timestamp" UNITS="s" TN="466" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="load_one" VAL="1.00" TYPE="float" UNITS="" TN="30" TMAX="70" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="os_release" VAL="2.6.10-sara3" TYPE="string" UNITS="" TN="628" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="disk_total" VAL="142.428" TYPE="double" UNITS="GB" TN="436" TMAX="1200" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_idle" VAL="49.9" TYPE="float" UNITS="%" TN="35" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_user" VAL="49.9" TYPE="float" UNITS="%" TN="85" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="swap_free" VAL="2074136" TYPE="uint32" UNITS="KB" TN="122" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Link_downed_counter" VAL="2" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Port_transmit_discards" VAL="3" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="pkts_out" VAL="0.49" TYPE="float" UNITS="packets/sec" TN="123" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="mem_cached" VAL="201720" TYPE="uint32" UNITS="KB" TN="124" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="load_five" VAL="1.00" TYPE="float" UNITS="" TN="255" TMAX="325" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_num" VAL="2" TYPE="uint16" UNITS="" TN="236" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="load_fifteen" VAL="1.00" TYPE="float" UNITS="" TN="507" TMAX="950" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_data" VAL="4294967295" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="mem_free" VAL="1459112" TYPE="uint32" UNITS="KB" TN="150" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_transmit_data" VAL="4294967295" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Port_receive_switch_relay_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="cpu_system" VAL="0.1" TYPE="float" UNITS="%" TN="21" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_remote_physical_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="proc_run" VAL="1" TYPE="uint32" UNITS="" TN="543" TMAX="950" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Excessive_buffer_overrun_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Link_error_recovery_counter" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="mem_total" VAL="2075696" TYPE="uint32" UNITS="KB" TN="929" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="cpu_aidle" VAL="50.0" TYPE="float" UNITS="%" TN="115" TMAX="3800" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_transmit_constrain_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="bytes_in" VAL="7859.65" TYPE="float" UNITS="bytes/sec" TN="14" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_packets" VAL="4294967295" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Port_receive_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="mem_buffers" VAL="0" TYPE="uint32" UNITS="KB" TN="178" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="mem_shared" VAL="0" TYPE="uint32" UNITS="KB" TN="14" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="swap_total" VAL="2097136" TYPE="uint32" UNITS="KB" TN="486" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="part_max_used" VAL="41.8" TYPE="float" UNITS="%" TN="142" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Local_link_integrity_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
</HOST>
<HOST NAME="gb-r6n15.irc.sara.nl" IP="192.168.17.111" REPORTED="1111153053" TN="27" TMAX="20" DMAX="0" LOCATION="unspecified" GMOND_STARTED="1108725371">
<METRIC NAME="disk_free" VAL="139.448" TYPE="double" UNITS="GB" TN="24" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="mtu" VAL="1500" TYPE="uint32" UNITS="B" TN="478" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="machine_type" VAL="x86" TYPE="string" UNITS="" TN="843" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="bytes_out" VAL="135.36" TYPE="float" UNITS="bytes/sec" TN="97" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="gexec" VAL="OFF" TYPE="string" UNITS="" TN="66" TMAX="300" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="proc_total" VAL="66" TYPE="uint32" UNITS="" TN="105" TMAX="950" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_constrain_errors" VAL="0" TYPE="uint32" UNITS="" TN="21" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="pkts_in" VAL="99.78" TYPE="float" UNITS="packets/sec" TN="74" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_nice" VAL="0.0" TYPE="float" UNITS="%" TN="69" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_speed" VAL="3393" TYPE="uint32" UNITS="MHz" TN="772" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="boottime" VAL="1108725349" TYPE="timestamp" UNITS="s" TN="928" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Symbol_error_counter" VAL="41" TYPE="uint32" UNITS="" TN="21" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_VL15_dropped" VAL="0" TYPE="uint32" UNITS="" TN="21" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Port_transmit_packets" VAL="4294967295" TYPE="uint32" UNITS="" TN="21" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="os_name" VAL="Linux" TYPE="string" UNITS="" TN="434" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="sys_clock" VAL="1108725371" TYPE="timestamp" UNITS="s" TN="1080" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="load_one" VAL="0.00" TYPE="float" UNITS="" TN="73" TMAX="70" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="os_release" VAL="2.6.10-sara3" TYPE="string" UNITS="" TN="612" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="disk_total" VAL="142.428" TYPE="double" UNITS="GB" TN="484" TMAX="1200" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_idle" VAL="99.9" TYPE="float" UNITS="%" TN="58" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_user" VAL="0.0" TYPE="float" UNITS="%" TN="32" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="swap_free" VAL="2082904" TYPE="uint32" UNITS="KB" TN="84" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Link_downed_counter" VAL="4" TYPE="uint32" UNITS="" TN="21" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Port_transmit_discards" VAL="3" TYPE="uint32" UNITS="" TN="21" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="pkts_out" VAL="1.24" TYPE="float" UNITS="packets/sec" TN="214" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="mem_cached" VAL="1108616" TYPE="uint32" UNITS="KB" TN="153" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="load_five" VAL="0.00" TYPE="float" UNITS="" TN="238" TMAX="325" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_num" VAL="2" TYPE="uint16" UNITS="" TN="246" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="load_fifteen" VAL="0.00" TYPE="float" UNITS="" TN="728" TMAX="950" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_data" VAL="4294967295" TYPE="uint32" UNITS="" TN="21" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="mem_free" VAL="779980" TYPE="uint32" UNITS="KB" TN="122" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_transmit_data" VAL="4294967295" TYPE="uint32" UNITS="" TN="21" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Port_receive_switch_relay_errors" VAL="0" TYPE="uint32" UNITS="" TN="21" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="cpu_system" VAL="0.0" TYPE="float" UNITS="%" TN="58" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_remote_physical_errors" VAL="0" TYPE="uint32" UNITS="" TN="21" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="proc_run" VAL="0" TYPE="uint32" UNITS="" TN="131" TMAX="950" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Excessive_buffer_overrun_errors" VAL="0" TYPE="uint32" UNITS="" TN="21" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Link_error_recovery_counter" VAL="0" TYPE="uint32" UNITS="" TN="21" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="mem_total" VAL="2075696" TYPE="uint32" UNITS="KB" TN="544" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="cpu_aidle" VAL="54.2" TYPE="float" UNITS="%" TN="913" TMAX="3800" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_transmit_constrain_errors" VAL="0" TYPE="uint32" UNITS="" TN="21" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="bytes_in" VAL="7871.65" TYPE="float" UNITS="bytes/sec" TN="24" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_packets" VAL="4294967295" TYPE="uint32" UNITS="" TN="21" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Port_receive_errors" VAL="0" TYPE="uint32" UNITS="" TN="21" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="mem_buffers" VAL="0" TYPE="uint32" UNITS="KB" TN="12" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="mem_shared" VAL="0" TYPE="uint32" UNITS="KB" TN="130" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="swap_total" VAL="2097136" TYPE="uint32" UNITS="KB" TN="201" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="part_max_used" VAL="41.8" TYPE="float" UNITS="%" TN="74" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Local_link_integrity_errors" VAL="0" TYPE="uint32" UNITS="" TN="21" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
</HOST>
<HOST NAME="gb-r10n3.irc.sara.nl" IP="192.168.17.162" REPORTED="1111153062" TN="18" TMAX="20" DMAX="0" LOCATION="unspecified" GMOND_STARTED="1110730709">
<METRIC NAME="disk_free" VAL="139.456" TYPE="double" UNITS="GB" TN="63" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="mtu" VAL="1500" TYPE="uint32" UNITS="B" TN="76" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="machine_type" VAL="x86" TYPE="string" UNITS="" TN="853" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="bytes_out" VAL="141.97" TYPE="float" UNITS="bytes/sec" TN="22" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="gexec" VAL="OFF" TYPE="string" UNITS="" TN="267" TMAX="300" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="proc_total" VAL="67" TYPE="uint32" UNITS="" TN="32" TMAX="950" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_constrain_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="pkts_in" VAL="169.00" TYPE="float" UNITS="packets/sec" TN="193" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_nice" VAL="0.0" TYPE="float" UNITS="%" TN="48" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_speed" VAL="3393" TYPE="uint32" UNITS="MHz" TN="152" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="boottime" VAL="1108725378" TYPE="timestamp" UNITS="s" TN="562" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Symbol_error_counter" VAL="26" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_VL15_dropped" VAL="0" TYPE="uint32" UNITS="" TN="23" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Port_transmit_packets" VAL="4294967295" TYPE="uint32" UNITS="" TN="23" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="os_name" VAL="Linux" TYPE="string" UNITS="" TN="295" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="sys_clock" VAL="1110730709" TYPE="timestamp" UNITS="s" TN="110" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="load_one" VAL="2.32" TYPE="float" UNITS="" TN="77" TMAX="70" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="os_release" VAL="2.6.10-sara3" TYPE="string" UNITS="" TN="340" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="disk_total" VAL="142.428" TYPE="double" UNITS="GB" TN="130" TMAX="1200" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_idle" VAL="0.0" TYPE="float" UNITS="%" TN="11" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_user" VAL="99.7" TYPE="float" UNITS="%" TN="62" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="swap_free" VAL="1759556" TYPE="uint32" UNITS="KB" TN="75" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Link_downed_counter" VAL="3" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Port_transmit_discards" VAL="3" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="pkts_out" VAL="1.31" TYPE="float" UNITS="packets/sec" TN="53" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="mem_cached" VAL="51244" TYPE="uint32" UNITS="KB" TN="139" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="load_five" VAL="2.08" TYPE="float" UNITS="" TN="332" TMAX="325" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_num" VAL="2" TYPE="uint16" UNITS="" TN="766" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="load_fifteen" VAL="2.01" TYPE="float" UNITS="" TN="58" TMAX="950" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_data" VAL="4294967295" TYPE="uint32" UNITS="" TN="23" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="mem_free" VAL="22280" TYPE="uint32" UNITS="KB" TN="29" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_transmit_data" VAL="4294967295" TYPE="uint32" UNITS="" TN="23" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Port_receive_switch_relay_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="cpu_system" VAL="0.3" TYPE="float" UNITS="%" TN="75" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_remote_physical_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="proc_run" VAL="2" TYPE="uint32" UNITS="" TN="317" TMAX="950" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Excessive_buffer_overrun_errors" VAL="0" TYPE="uint32" UNITS="" TN="23" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Link_error_recovery_counter" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="mem_total" VAL="2075696" TYPE="uint32" UNITS="KB" TN="280" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="cpu_aidle" VAL="44.2" TYPE="float" UNITS="%" TN="2898" TMAX="3800" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_transmit_constrain_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="bytes_in" VAL="7946.24" TYPE="float" UNITS="bytes/sec" TN="15" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_packets" VAL="4294967295" TYPE="uint32" UNITS="" TN="23" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Port_receive_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="mem_buffers" VAL="0" TYPE="uint32" UNITS="KB" TN="34" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="mem_shared" VAL="0" TYPE="uint32" UNITS="KB" TN="124" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="swap_total" VAL="2097136" TYPE="uint32" UNITS="KB" TN="714" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="part_max_used" VAL="41.6" TYPE="float" UNITS="%" TN="160" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Local_link_integrity_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
</HOST>
<HOST NAME="gb-r2n8.irc.sara.nl" IP="192.168.17.28" REPORTED="1111153067" TN="13" TMAX="20" DMAX="0" LOCATION="unspecified" GMOND_STARTED="1109582193">
<METRIC NAME="disk_free" VAL="139.451" TYPE="double" UNITS="GB" TN="177" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="mtu" VAL="1500" TYPE="uint32" UNITS="B" TN="994" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="machine_type" VAL="x86" TYPE="string" UNITS="" TN="519" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="bytes_out" VAL="150.39" TYPE="float" UNITS="bytes/sec" TN="227" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="gexec" VAL="OFF" TYPE="string" UNITS="" TN="188" TMAX="300" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="proc_total" VAL="76" TYPE="uint32" UNITS="" TN="216" TMAX="950" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_constrain_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="pkts_in" VAL="99.00" TYPE="float" UNITS="packets/sec" TN="96" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_nice" VAL="0.0" TYPE="float" UNITS="%" TN="40" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_speed" VAL="3392" TYPE="uint32" UNITS="MHz" TN="215" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="boottime" VAL="1109582168" TYPE="timestamp" UNITS="s" TN="343" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Symbol_error_counter" VAL="16" TYPE="uint32" UNITS="" TN="25" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_VL15_dropped" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Port_transmit_packets" VAL="4294967295" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="os_name" VAL="Linux" TYPE="string" UNITS="" TN="491" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="sys_clock" VAL="1109582193" TYPE="timestamp" UNITS="s" TN="948" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="load_one" VAL="1.01" TYPE="float" UNITS="" TN="27" TMAX="70" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="os_release" VAL="2.6.10-sara3" TYPE="string" UNITS="" TN="69" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="disk_total" VAL="142.428" TYPE="double" UNITS="GB" TN="979" TMAX="1200" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_idle" VAL="50.0" TYPE="float" UNITS="%" TN="68" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_user" VAL="50.2" TYPE="float" UNITS="%" TN="65" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="swap_free" VAL="2082084" TYPE="uint32" UNITS="KB" TN="122" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Link_downed_counter" VAL="2" TYPE="uint32" UNITS="" TN="25" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Port_transmit_discards" VAL="5" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="pkts_out" VAL="1.29" TYPE="float" UNITS="packets/sec" TN="110" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="mem_cached" VAL="413552" TYPE="uint32" UNITS="KB" TN="82" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="load_five" VAL="1.03" TYPE="float" UNITS="" TN="175" TMAX="325" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_num" VAL="2" TYPE="uint16" UNITS="" TN="419" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="load_fifteen" VAL="1.00" TYPE="float" UNITS="" TN="68" TMAX="950" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_data" VAL="4294967295" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="mem_free" VAL="1247900" TYPE="uint32" UNITS="KB" TN="101" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_transmit_data" VAL="4294967295" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Port_receive_switch_relay_errors" VAL="0" TYPE="uint32" UNITS="" TN="25" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="cpu_system" VAL="0.1" TYPE="float" UNITS="%" TN="57" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_remote_physical_errors" VAL="0" TYPE="uint32" UNITS="" TN="25" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="proc_run" VAL="1" TYPE="uint32" UNITS="" TN="428" TMAX="950" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Excessive_buffer_overrun_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Link_error_recovery_counter" VAL="0" TYPE="uint32" UNITS="" TN="25" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="mem_total" VAL="2075696" TYPE="uint32" UNITS="KB" TN="145" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="cpu_aidle" VAL="51.1" TYPE="float" UNITS="%" TN="1764" TMAX="3800" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_transmit_constrain_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="bytes_in" VAL="8278.23" TYPE="float" UNITS="bytes/sec" TN="30" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_packets" VAL="4294967295" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="hca1_port1_Port_receive_errors" VAL="0" TYPE="uint32" UNITS="" TN="25" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="mem_buffers" VAL="0" TYPE="uint32" UNITS="KB" TN="82" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="mem_shared" VAL="0" TYPE="uint32" UNITS="KB" TN="31" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="swap_total" VAL="2097136" TYPE="uint32" UNITS="KB" TN="412" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="part_max_used" VAL="41.8" TYPE="float" UNITS="%" TN="17" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Local_link_integrity_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
</HOST>
<HOST NAME="gb-r1n1.irc.sara.nl" IP="192.168.17.2" REPORTED="1111153061" TN="19" TMAX="20" DMAX="0" LOCATION="unspecified" GMOND_STARTED="1108725330">
<METRIC NAME="disk_free" VAL="139.344" TYPE="double" UNITS="GB" TN="28" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="mtu" VAL="1500" TYPE="uint32" UNITS="B" TN="441" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="machine_type" VAL="x86" TYPE="string" UNITS="" TN="731" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="bytes_out" VAL="127.65" TYPE="float" UNITS="bytes/sec" TN="29" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="gexec" VAL="OFF" TYPE="string" UNITS="" TN="12" TMAX="300" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="proc_total" VAL="66" TYPE="uint32" UNITS="" TN="334" TMAX="950" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Port_receive_constrain_errors" VAL="0" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>
<METRIC NAME="pkts_in" VAL="89.46" TYPE="float" UNITS="packets/sec" TN="256" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_nice" VAL="0.0" TYPE="float" UNITS="%" TN="34" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond"/>
<METRIC NAME="cpu_speed" VAL="3392" TYPE="uint32" UNITS="MHz" TN="74" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="boottime" VAL="1108725306" TYPE="timestamp" UNITS="s" TN="1114" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond"/>
<METRIC NAME="hca1_port1_Symbol_error_counter" VAL="18" TYPE="uint32" UNITS="" TN="24" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmetric"/>